services:
  database-api:
    image: mysql:latest
    restart: always
    container_name: database-api
    environment:
      MYSQL_ROOT_PASSWORD: ${USERNAME}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - serial
 
volumes:
  db_data:

networks:
  serial:
    driver: bridge


