services:
  database-api:
    image: mysql:8
    container_name: database-api
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: condominium
      MYSQL_USER: condominium
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - kanastra

volumes:
  db_data:


networks:
  kanastra:
    driver: bridge
