"""Initial migration

Revision ID: 0f3dccb5e9d4
Revises: 2ce9e3cfa7e3
Create Date: 2025-03-05 15:52:17.124435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3dccb5e9d4'
down_revision: Union[str, None] = '2ce9e3cfa7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
