"""Initial migration

Revision ID: 14f2449ce31b
Revises: d043e070bd30
Create Date: 2025-03-03 15:39:24.485877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f2449ce31b'
down_revision: Union[str, None] = 'd043e070bd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('authorization_day', sa.Date(), nullable=True),
    sa.Column('hour_start', sa.String(length=5), nullable=True),
    sa.Column('hour_end', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorizations_id'), 'authorizations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorizations_id'), table_name='authorizations')
    op.drop_table('authorizations')
    # ### end Alembic commands ###
