"""Initial migration

Revision ID: 2ce9e3cfa7e3
Revises: 87974842a017
Create Date: 2025-03-05 15:52:11.845211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce9e3cfa7e3'
down_revision: Union[str, None] = '87974842a017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peoples', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peoples', 'password')
    # ### end Alembic commands ###
