"""Initial migration

Revision ID: 53e1e0ca2990
Revises: 8ddbc0a1a779
Create Date: 2025-03-03 16:13:25.288138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e1e0ca2990'
down_revision: Union[str, None] = '8ddbc0a1a779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
