"""Initial migration

Revision ID: 7a7a7f135a7e
Revises: d7f22f6a00bf
Create Date: 2025-03-03 16:03:30.026682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7a7f135a7e'
down_revision: Union[str, None] = 'd7f22f6a00bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
