"""Initial migration

Revision ID: 8ddbc0a1a779
Revises: 6a187264bee3
Create Date: 2025-03-03 16:13:19.655081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddbc0a1a779'
down_revision: Union[str, None] = '6a187264bee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorizations', sa.Column('authorization_date', sa.Date(), nullable=True))
    op.drop_column('authorizations', 'authorization_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorizations', sa.Column('authorization_day', sa.DATE(), nullable=True))
    op.drop_column('authorizations', 'authorization_date')
    # ### end Alembic commands ###
