"""Initial migration

Revision ID: b518835f5fa4
Revises: f4795a94a701
Create Date: 2025-03-05 08:11:09.292286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b518835f5fa4'
down_revision: Union[str, None] = 'f4795a94a701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('picture', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'picture')
    # ### end Alembic commands ###
