"""Initial migration

Revision ID: bb7cf22685de
Revises: 53e1e0ca2990
Create Date: 2025-03-03 16:16:45.909748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb7cf22685de'
down_revision: Union[str, None] = '53e1e0ca2990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authorizations', 'hour_start',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('authorizations', 'hour_end',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authorizations', 'hour_end',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('authorizations', 'hour_start',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
